### PR TITLE
Update helm chart params, remove warning about Helm repo, fix redirect

### LINKED ISSUE #758: Remove the deprecation notice about Helm repository and fix broken links
## Description
After repository transfer, we added a deprecation notice in [this PR](https://github.com/kubeshop/botkube-docs/pull/88).

Before releasing 0.14 we should remove it as it was there for ~3months.

Additionally, we need to fix broken links on integration images. The problem is simple to reproduce. 
Go to https://botkube.io, click `Try Now` and try to click any of the communicator icons. You will get `Not Found` error.

Reason: We don't have a trailing slash, so the last sub-path is replaced instead of appending to URL.

### PR DESCRIPTION
**Pull request by mszostok**
## Description

Changes proposed in this pull request:

- Update helm chart params, 
- Remove warning about Helm repo, 
- Fix redirects. This probably can be fixed in a better way, but the problem is simple to reproduce. Go to `botkube.io`, click `Try Now` and try to click any of the communicator icons. We don't have a trailing slash so the last sub-path is replaced instead of appending to url.

Preview URL: https://fix-links.botkube-docs.pages.dev/

## Issue
Fixes https://github.com/kubeshop/botkube/issues/758

### CODE REVIEW

File: src/components/Hero/index.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ export const Hero = () => {
         <p className="hero__subtitle">A messaging bot for monitoring and debugging Kubernetes clusters.</p>
         <div className={styles.mainSloganLinks}>
           <Link
-            to={useBaseUrl("/docs/installation")}
+            to={useBaseUrl("/docs/installation/")}
```
Comment (madebyrogal) [inline src/components/Hero/index.tsx:19]: This is fine either with or without "/" Docusaurus handles it correctly. The problem is in IntegrationList component, replace the code with this.
`src/components/IntegrationList/index.tsx`

```
export const IntegrationList = (props: Props) => {
  const { integrations = [] } = props;
  const currentPath = window.location.pathname.replace(/\/$|$/, "/");

  return (
    <div className={styles.integrations}>
      {integrations.map(integration => (
        <div key={integration.name} className={styles.integrationsItem}>
          <Link to={`${currentPath}${integration.link}`} className="integrations__link">
            <img src={integration.image} alt={integration.name} className="integrations__image" />
            {integration.name}
          </Link>
        </div>
      ))}
    </div>
  );
};
```

**Review by madebyrogal — APPROVED** [review]
Your solution is ok but the problem is in IntegrationList component. So if you will fix it there it won't repeat again.

File: src/components/Hero/index.tsx (hunk 1 above)
Comment (mszostok) [reply src/components/Hero/index.tsx]: Ok, I tried to use that, however the CI fails with such error: https://github.com/kubeshop/botkube-docs/actions/runs/3127760256/jobs/5074760131

When I revert that, CI is green.
